import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import CustomCursor from "@/components/ui/CustomCursor";
import { Navbar } from "@/components/pages/Navbar/Navbar";
import { Footer } from "@/components/pages/Footer/Footer";
import { StarBackground } from "@/components/pages/Background/Starbackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vedang Dhuri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <link rel="icon" href="/img/top_icon.png" />
      </head>
      <body
        className={`${inter.className} bg-black text-white overflow-x-hidden`}
      >
        <StarBackground />
        {/* <CustomCursor /> */}
        <Navbar />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
